### ISSUE TITLE
UMMobClick/MobClick.h file not found

### ISSUE THREAD

**Issue by openproject** [pedia/flutter_umeng_analytics#1]
pub.flutter-io.cn/flutter_umeng_analytics-0.0.1/ios/Classes/FlutterUmengAnalyticsPlugin.m:3:9: fatal error: 'UMMobClick/MobClick.h' file not found

is a bug or my wrong usage? need help.

**Comment by pedia** [comment]
These files generated by cocoapods.
Did pod install succeeded?

**Comment by openproject** [comment]
yes，the header can found in app, but in flutter plugin not found

**Comment by pedia** [comment]
Maybe helped, run this:
```bash
FLUTTER_FRAMEWORK_DIR=/path/to/flutter/bin/cache/artifacts/engine/ios pod install
```
Remember to replace path/to your folder of flutter.
