### ISSUE TITLE
包错误

### ISSUE THREAD

**Issue by 370966584** [pedia/flutter_umeng_analytics#5]
![image](https://user-images.githubusercontent.com/26058251/56954292-058b4300-6b71-11e9-839a-43a8b719ba6b.png)

**Comment by flyuuo9** [comment]
@370966584 请问怎么解决的？遇到同样的问题了
com.umeng.analytics 不存在

**Comment by 370966584** [comment]
> @370966584 请问怎么解决的？遇到同样的问题了
> com.umeng.analytics 不存在

好像 是 AndroidX的问题。你使用0.0.1试试

**Comment by 370966584** [comment]
> @370966584 请问怎么解决的？遇到同样的问题了
> com.umeng.analytics 不存在

好像是androidX的问题，你切换到0.0.1试试，或使用example试下

**Comment by flyuuo9** [comment]
> > @370966584 请问怎么解决的？遇到同样的问题了
> > com.umeng.analytics 不存在
> 
> 好像是androidX的问题，你切换到0.0.1试试，或使用example试下

0.01不支持dart2吧 才用的0.0.2

**Comment by zoujinbin** [comment]
各位兄弟，这个问题怎么解决的

**Comment by lujiayi1228** [comment]
![image](https://user-images.githubusercontent.com/26211081/64502045-9b409700-d2f6-11e9-9d99-1e80b569ee78.png)
![image](https://user-images.githubusercontent.com/26211081/64502128-f2df0280-d2f6-11e9-91bd-144792e7b429.png)
