### ISSUE TITLE
安卓的统计不了，后台看不到统计数据，埋点也报错

### ISSUE THREAD

**Issue by 370966584** [pedia/flutter_umeng_analytics#6]
![image](https://user-images.githubusercontent.com/26058251/57421951-908ace00-7240-11e9-9ed7-2eee657857ca.png)

**Comment by 424626154** [comment]
～/flutter_umeng_analytics-0.0.2/android/build.gradle
37行注释打开
api  'com.umeng.analytics:analytics:latest.integration'

**Comment by lujiayi1228** [comment]
注释打开的~还是没有统计~iOS有统计
